### ISSUE TITLE
Non-passwordless route path helpers are prefixed with /users when rendering passwordless templates

### ISSUE THREAD

**Issue by abevoelker** [mikker/passwordless#30]
Given this routes file:

```ruby
# config/routes.rb
Rails.application.routes.draw do
  resources :stripe_charges, only: [:create]
  passwordless_for :users
end
```

And this application layout (`app/views/layouts/application.html.erb`):

```erb
<!DOCTYPE html>
<html>
  <head>
    <title>foo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <nav>
      <form action="<%= stripe_charges_path %>" method="POST"></form>
    </nav>
    <%= yield %>
  </body>
</html>
```

When the application layout is rendered on normal pages, `stripe_charges_path` correctly returns `/stripe_charges`, but when rendered as part of a Passwordless template like `app/views/passwordless/sessions/new.html.erb`, it is returning `/users/stripe_charges`, which doesn't exist.

**Comment by mikker** [comment]
This is due to Passwordless _isolating its engine namespace_. In your case, every view rendered by a Passwordless action (including the layout) has to prefix the main app's routes with `main_app.` eg. `main_app.stripe_charges_path`.

It's really annoying and I've been looking into removing the isolation, see #22.

I don't know when I'll have the time to finalize it though – PRs very welcome.

**Comment by abevoelker** [comment]
Got it, thanks for the explanation!
