### ISSUE TITLE
Mailer previews

### ISSUE THREAD

**Issue by dankimio** [mikker/passwordless#66]

**Comment by mikker** [comment]
I have no idea whether a gem can bundle mailer previews. As this has very close to no information, I'll take it as a (fairly useless) feature request.
To be honest I'd expect most users to overwrite the bundled views sooner or later and then they can fittingly create their own previews.

Closing this not because I'm rejecting the idea but more because it isn't very useful without further information.

**Comment by keilmillerjr** [comment]
https://github.com/ryanb/letter_opener
